### ISSUE TITLE
Update not downloading

### ISSUE THREAD

**Issue by fndrsm** [RainbowCookie32/rusty-psn#137]
Hi dev, wanna ask.

This is my first time using rusty-psn, as the tool recommended by RPCS3 wiki. I have 3 games on my RPCS3

1. Batman - Arkham City (Europe) - BLES00926
2. Need for Speed - Most Wanted - A Criterion Game (USA) - BLUS31010
3. Red Dead Redemption GOTY - BLES01294

All the game have updates when i check on rusty-psn, but when i press the download/download all button. Nothing happen, the progress was stuck on 0%.

![image](https://github.com/RainbowCookie32/rusty-psn/assets/48046968/239d039e-ed48-4cab-bac1-1b60783c4a7d)

So, do you have any suggestion for this. I completely newbie, i don't know if this was normal as the game server is down or just i did something wrong.

Thanks

**Comment by RainbowCookie32** [comment]
Hi! rusty-psn should create a ´session_log´ file on the same folder the executable is placed, please post it here so I can take a look and check if something went wrong.

**Comment by fndrsm** [comment]
[session_log.log](https://github.com/RainbowCookie32/rusty-psn/files/11437858/session_log.log)

**Comment by RainbowCookie32** [comment]
I should add more logging to be fair, but as far as I can tell it's downloading the files just fine. Looking at the screenshot, it seems like it actually finished downloading the update for Batman Arkham Asylum. Can you see update files on the ´pkgs´ folder?

I also checked on my side with the latest released, extracted on a folder on my desktop and it downloaded the updates without issues. Just in case, where did you extract rusty-psn to?

**Comment by fndrsm** [comment]
Every folder and file was created by rusty-psn on the 'pkgs' folder, but only 0KB file inside. I extract the rusty-psn on my external hardisk with RPCS3 and all the PS3 games.

Could my ISP be the problem? But opening website was fine. I don't have active VPN or DNS right now.

**Comment by RainbowCookie32** [comment]
It shouldn't be, since it *is* downloading something. The question is what it's doing with that data, since it's clearly not really getting to the file. Not all of it at least.

I'll take a better look at it in the morning, probably gonna put together a build with more logging to try to throw some light into this.

**Comment by fndrsm** [comment]
I see, really appreciate it. Thank you very much for the help.

**Comment by RainbowCookie32** [comment]
Alright, try this build https://github.com/RainbowCookie32/rusty-psn/actions/runs/4940209206

Nothing should change, but I added a bit more logging to try to see what it's doing. It seems to be getting stuck on the download loop for some reason, since there are more log messages when it exits that loop, but your log doesn't show any of them so it's stuck.

For testing, run rusty-psn and try to download one of the problematic updates, then close it and post the session log here. Do just one file so the log stays more readable.

**Comment by fndrsm** [comment]
Hi, good morning from here, here is the file.
[session_log.log](https://github.com/RainbowCookie32/rusty-psn/files/11446830/session_log.log)

**Comment by RainbowCookie32** [comment]
Well that's slightly annoying. It seems to just *get stuck* waiting for the next chunk of data. Never errors out, but never completes either. Might be some external factor interfering, but no idea what exactly it could be.

**Comment by RainbowCookie32** [comment]
Thanks :) Let me know if you find a solution for it.

**Comment by fndrsm** [comment]
Hi dev, just let you know, for sure, my WIFI ISP was the **root cause**. First i try to check if i have DNS on my laptop. And actually i have (Google DNS), i turned off, but still the download not make any progress.

So i use my mobile hotspot but with my data carrier, and it works, but the speed only 200kbps (dunno if my speed is bad or the server is heavy). 

![image](https://github.com/RainbowCookie32/rusty-psn/assets/48046968/7acb32d3-a69c-4b37-bc0a-84741a85925d)
![image](https://github.com/RainbowCookie32/rusty-psn/assets/48046968/bc2d8560-cd96-4dfa-8c4c-c251513dbc1e)


I tested it with and windows sandbox, on my actual windows it's failed on 20% don't know why.

`Fun fact : My ISP, the WI-FI and the carrier is the same company but with different sub brands even they are using the same networks.`

**Comment by RainbowCookie32** [comment]
So, it's potentially an ISP issue. If you try to download it manually ([link here](http://b0.ww.np.dl.playstation.net/tppkg/np/BLES00926/BLES00926_T3/b77a39b248e5876c/EP1018-BLES00926_00-ARKHAMCITY0PATCH-A0104-V0100-PE.pkg)) on the problematic wifi network, does it work? 24.7MB file, it's the update file for BLES00926

**Comment by fndrsm** [comment]
> Yeaaaaaah, my ISP sucks, look ![Screenshot_20230512-215038_Chrome.png](https://github.com/RainbowCookie32/rusty-psn/assets/48046968/ae0bf6de-2854-4857-88f2-287a93ba7f7f)
> 
> Stuck on 90kb downloading.

I'm really sorry dev, i thought it was software/server/hardware issues but turns out my ISP 😵.

But really thanks for your help tho.

**Comment by RainbowCookie32** [comment]
No problem, sucks that your ISP sucks. That's a bit more difficult to fix 😅
