### ISSUE TITLE
rusty-psn will not download updates on any version despite being allowed to by the firewall

### ISSUE THREAD

**Issue by oxycodo** [RainbowCookie32/rusty-psn#158]
like the title states, it wont download the files and consalty pops up with error and failed prompts.
![Screenshot 2023-07-27 200153](https://github.com/RainbowCookie32/rusty-psn/assets/140770028/9c17835d-a742-4454-92ee-bb5532225afe)
![image](https://github.com/RainbowCookie32/rusty-psn/assets/140770028/776a0f2b-d6d4-4ef0-8c8f-da995b4b35c7)

**Comment by RainbowCookie32** [comment]
Where did you extract rusty-psn to? The access denied error probably means it doesn't have permission to write to that directory to save the downloaded files

**Comment by oxycodo** [comment]
that worked. it was going to a duplicate /pkgs folder which i deleted earlier without knowing. redid the download and created a new folder and saved it.
