### ISSUE TITLE
2.1 GUI for Windows is triggering Microsoft Defender

### ISSUE THREAD

**Issue by clemon79** [RainbowCookie32/rusty-psn#18]
It's finding this: https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aScript%2fWacatac.B!ml&threatid=2147735503

**Comment by RainbowCookie32** [comment]
Huh, indeed it does. Interesting🤔

I'll look around and see if I can do anything about it. For what it's worth, it's a false positive as far as I can tell, since I can't really remember coding in a Trojan

**Comment by RainbowCookie32** [comment]
Looked a bit more into it, it's a machine learning-based detection (see the !ml at the end). While it's a nice feature, it's a bit of false positive hell sometimes.

I pushed a version bump and downloading the resulting zip and Defender seems happy about it, so I'll push a new release to (hopefully) get around it.

**Comment by RainbowCookie32** [comment]
[Release pushed](https://github.com/RainbowCookie32/rusty-psn/releases/tag/v0.2.2), should be fixed. Ping to reopen if that's not the case.
