### ISSUE TITLE
Feature Request Retain Search Results

### ISSUE THREAD

**Issue by Darkhost1999** [RainbowCookie32/rusty-psn#2]
![image](https://user-images.githubusercontent.com/60384196/162812716-904df0cc-789b-46e6-8483-7c8812c9abb1.png)

On reboot of the .exe keep all successful search results from all previous sessions.
This might be out of intended scope yet is quality of life improvements instead of searching 30+ game IDs over and over if you are the kind to delete pkgs after install.
Feel free to Won't fix if desired.

**Comment by RainbowCookie32** [comment]
Might add it as an opt-in setting in the new Settings dialog tomorrow. The slightly annoying groundwork was mostly taken care of with custom download paths.

**Comment by RainbowCookie32** [comment]
Well, I tried.

I seem to be hitting some error when deserializing the saved search results, but egui swallows the error so I don't know exactly what's broken. Might look more into it further down the line, not feeling like going down this rabbithole right now.

**Comment by Darkhost1999** [comment]
No problem, take as long as you need. A feature like this is just nice to have. But how often does someone practically need to search 30 games of updates repeatedly.

**Comment by Darkhost1999** [comment]
I don't want this on my list anymore. Especially don't need the "slightly annoying" label even if it is pertaining to me or not.

**Comment by RainbowCookie32** [comment]
lol ok
