### ISSUE TITLE
Download Failed 

### ISSUE THREAD

**Issue by Sackedball** [RainbowCookie32/rusty-psn#216]
Hi,
I was updating GT5(BCUS98114) and one version just refused to get downloaded (Update ver 02.00)

Error- ( Error downloading update: hash mismatch on downloaded file. )
![image](https://github.com/RainbowCookie32/rusty-psn/assets/167522482/55d0a543-8a4b-47c9-a933-b0ba2761ad0c)

Also 
Is it normal for it to use 100% of my Gpu😅
![image](https://github.com/RainbowCookie32/rusty-psn/assets/167522482/4c958e22-2781-4b05-81bc-abe4ee88e576)

**Comment by RainbowCookie32** [comment]
Hash mismatch means the file got corrupted during the download, sometimes Sony's servers like to do that. I'd recommend waiting a bit and trying again, maybe post a log if it still refuses to cooperate.

Regarding GPU usage, I suspect that comes from my (admittedly lazy) workaround for the UI to stay updated while downloading packages. Didn't expect it to hit 100% usage tho, what's your GPU?

**Comment by RainbowCookie32** [comment]
Just checked on my PC with the latest rusty-psn build and it downloads fine, so it's likely Sony's servers are being unreliable.
![image](https://github.com/RainbowCookie32/rusty-psn/assets/16805474/ee077c0e-0438-4cb0-bfc5-f3619faaf5e9)

Personally I haven't experienced this much, but I've seen others have this experience. The file being a bit larger probably doesn't help, not much to do here other than retry until you manage to get the whole thing properly.

I'll take a look at GPU usage though.

**Comment by Sackedball** [comment]
Thanks, @RainbowCookie32 I will try downloading it after a few days.
 My GPU is Gt 710  2 GB VRAM 😅

**Comment by RainbowCookie32** [comment]
Ah, that'd make sense. I'll try to stop being lazy and fix the update rate, but I wouldn't be surprised if you still got relatively high usage.

Regarding the rogue PKG, you can probably try again now and it might work. Don't think you should have to wait days.

**Comment by Sackedball** [comment]
Update 
It works 😁
![image](https://github.com/RainbowCookie32/rusty-psn/assets/167522482/f0ad844e-9cb8-4162-a7fa-ba94f8a68157)

**Comment by RainbowCookie32** [comment]
Awesome!
