### ISSUE TITLE
updates missing

### ISSUE THREAD

**Issue by gabrielalinda** [RainbowCookie32/rusty-psn#219]
i tried getting updates for little big planet 3 and everything was in order but the 1.13 update was missing 
i changed the download location but that just made more updates dissapear
help please

**Comment by RainbowCookie32** [comment]
I'm gonna need you to post a .log file after downloading an update that disappears

**Comment by RainbowCookie32** [comment]
For reference, that'd be a text file named rusty-psn_ and the date and hour when you launched the app, located alongside the .exe file.

![image](https://github.com/RainbowCookie32/rusty-psn/assets/16805474/37296505-c7d0-43e4-b0fd-a81a1e38f602)

Run rusty-psn, reproduce your issue, then close it and upload that file here.

**Comment by gabrielalinda** [comment]
the file is too big
how do i send it?

**Comment by RainbowCookie32** [comment]
If compressing the log file doesn't help, then upload it somewhere else (like Google drive) and post a link to it

**Comment by RainbowCookie32** [comment]
Is this still an issue? It's been a while
