### ISSUE TITLE
Error downloading an update for GT4

### ISSUE THREAD

**Issue by imnotanugget** [RainbowCookie32/rusty-psn#220]
[rusty-psn_2024-05-27_21-39-56.log](https://github.com/RainbowCookie32/rusty-psn/files/15463010/rusty-psn_2024-05-27_21-39-56.log)
Hello, i'm getting an error when i'm trying download update for gran turismo 5,
update version is v0200 and the error i'm getting is "Failed to download BCUS98114 v02.00: Hash mismatch. 
I can probably use older update no problem but wanted to report that's what's happening.

**Comment by RainbowCookie32** [comment]
Just tested locally and it downloaded without issues:

![image](https://github.com/RainbowCookie32/rusty-psn/assets/16805474/48d7e06c-c7b2-4eb3-9bb4-0b8b13a2cbf0)

It's likely the same case as #216, Sony's servers telling you bye-bye before the file is actually completed. You are gonna have to re-try and it should eventually complete properly, maybe wait a bit before your next attempt. I've had it happen before with updates and firmware, same for other users. Unfortunately, I don't think I can do much here.

I'll probably have to add a pop-up or something for these cases, and some extra logging for easier diagnostics.

**Comment by imnotanugget** [comment]
Yeah i tried multiple times but i figured that's the case. Thanks for prompt response.

**Comment by RainbowCookie32** [comment]
No problem! If you already re-tried, I'd suggest waiting a bit before trying again. A few hours, maybe a day. Or if it's really persistent, maybe trying to download the file manually works better, you can use the bot on RPCS3's discord server to get the link.

On my side, I should probably do a file size check to give a better warning about this edge case. If Sony's closing shop before the download is done, the file should be at least a bit smaller than planned.
