### ISSUE TITLE
missing update

### ISSUE THREAD

**Issue by Huhwhatisthat** [RainbowCookie32/rusty-psn#222]
An error comes up when installing updates for little big planet. Here's the Serial: BCES00611

The log file:
[rusty-psn_2024-06-13_18-17-09.log](https://github.com/user-attachments/files/15822978/rusty-psn_2024-06-13_18-17-09.log)
[rusty-psn_2024-06-13_18-17-09.log](https://github.com/user-attachments/files/15822978/rusty-psn_2024-06-13_18-17-09.log)
[rusty-psn_2024-06-13_18-17-09.log](https://github.com/user-attachments/files/15822978/rusty-psn_2024-06-13_18-17-09.log)

**Comment by RainbowCookie32** [comment]
Timeout errors, that's gonna be either your connection or Sony's servers having issues, or something in between. Just tried locally and the update downloaded fine, so I suggest trying again later.
