### ISSUE TITLE
Create Folder SerailID AND the name of the game

### ISSUE THREAD

**Issue by nkkky** [RainbowCookie32/rusty-psn#224]
For me it is quiet annoying and I hope you feel the same.

Rusty works always fine for me.
But when downloading an update Rusty-PSN creates a new folder only with Serial-ID.

For me it would be great if it could create the folder with Serial-ID AND game name like this:

![image](https://github.com/user-attachments/assets/98cbfd19-0adc-4c45-ade1-7dc375476abc)

Because. who of us can identify the game via the Serial-ID without cheating? :)

**Comment by RainbowCookie32** [comment]
Fair enough. In my defense, back when I started work on rusty-psn I could actually identify some games by their serials lol (and I still remember NPEB02436 is Persona 5).

I'll work on it today, should be out soon enough.

**Comment by RainbowCookie32** [comment]
Implemented in #225, will tag a new release once it's done building.

**Comment by nkkky** [comment]
Very cool mate.

Any plans to work with the RPCS3 guys together so you can implement these game update functions into RPCS3? 

I am still asking myself why the guys of RPCS3 still have not done it.

I always have to use Rusty.

**Comment by RainbowCookie32** [comment]
It was requested a bunch of times to implement fetching game updates to the emulator.

It's probably not done out of an abundance of caution. If someone at Sony wakes up one day feeling like third parties fetching updates from their servers is a no-go, I think we'd all rather have the external tools go down instead of the emulator lol

**Comment by nkkky** [comment]
Ok, it might be the case that some characters are not allowed in the folder name: 

![image](https://github.com/user-attachments/assets/b67aae0e-74c6-46c2-a4c3-6a72c6731218)

![image](https://github.com/user-attachments/assets/e7410fa5-aeac-441d-a941-06c535d66fc1)

**Comment by RainbowCookie32** [comment]
Indeed.

I was ~~lazy~~ hopeful no games would have special characters in their titles but they sure did. There's a new build that replaces non-alphanumeric characters. That's probably a bit overenthusiastic, but better safe than sorry lol
