### ISSUE TITLE
The directory name is invalid (God of War: Ascension)

### ISSUE THREAD

**Issue by FelesNoctis** [RainbowCookie32/rusty-psn#226]
**OS:** Windows 11
**Vrs:** 0.4.0 egui

The title of the game contains a colon ( **:** ), which Windows does not allow in file paths, so all downloads for this game (and similarly named ones) fail.

[rusty-psn_2024-08-05_01-28-27.log](https://github.com/user-attachments/files/16493054/rusty-psn_2024-08-05_01-28-27.log)

**Comment by RainbowCookie32** [comment]
Crap, I should've checked for a case like that. 

I'll try to fix it later today. In the meanwhile, you can use the previous release.

**Comment by rainonwires** [comment]
I have fixed this issue within my own repository, I will push to my master and make a request. Hopefully it is up to your standards first time making a contribution to a project like this.

**Comment by RainbowCookie32** [comment]
Should be fixed with v0.4.1 thanks to @rainonwires

**Comment by RainbowCookie32** [comment]
Following up on this, I changed the fix in 06229d854136718cdb5d6841ad39d11c49d5bd8f to target just the invalid characters for Windows/Linux instead of nuking everything that wasn't alphanumeric, spaces, or dashes. Initially it was out of concern for games with Japanese titles, but that turned out to be fine. Things like ™ (like in BCUS98208) were getting the axe unnecessarily though.

**Comment by rainonwires** [comment]
> Following up on this, I changed the fix in [06229d8](https://github.com/RainbowCookie32/rusty-psn/commit/06229d854136718cdb5d6841ad39d11c49d5bd8f) to target just the invalid characters for Windows/Linux instead of nuking everything that wasn't alphanumeric, spaces, or dashes. Initially it was out of concern for games with Japanese titles, but that turned out to be fine. Things like ™ (like in BCUS98208) were getting the axe unnecessarily though.

Good catch, I was completely oblivious to this possibility.

**Comment by saif77777777** [comment]
BCES01742
