### ISSUE TITLE
Unable to download updates using linux gui client on steam deck oled 512gb

### ISSUE THREAD

**Issue by FicMon** [RainbowCookie32/rusty-psn#227]
[rusty-psn_2024-08-05_18-40-09.log](https://github.com/user-attachments/files/16500526/rusty-psn_2024-08-05_18-40-09.log)
Also unable to download stuff off nopaystation because of a name resolution failure. Might be connected. Suddenly couldnt download anything on rust psn and nopaystation.

**Comment by RainbowCookie32** [comment]
> ConnectError("dns error", Custom { kind: Uncategorized, error: "failed to lookup address information: Temporary failure in name resolution" }

DNS issue on your side, or your DNS provider's. Also, please don't bring up piracy sites - it's unrelated to my tool and I'd really rather not have that here.
