### ISSUE TITLE
Question: An I correct in assuming this doesn't work in Windows 7? (rusty-psn-egui-windows-v0.4.6 doesn't start for me)

### ISSUE THREAD

**Issue by BurntAussieTyre** [RainbowCookie32/rusty-psn#245]
![rusty-psn-exe](https://github.com/user-attachments/assets/4138a928-d583-44a5-aab7-3f5ee70b1e5a)

**Comment by BurntAussieTyre** [comment]
PSA for anyone who wanted to know: v0.3.7 does the job in Win 7.

**Comment by BurntAussieTyre** [comment]
> While I don't do anything to block it on my code, or rely on newer Windows features, I can't speak for my dependencies.
> 
> I wouldn't support it regardless. It's time to stop being stubborn and quit using EoL systems.

Mate I still use XP to play Mechwarrior & Quake.

"EoL" is an illusionary corporate cage born from a late-stage capitalist civilization in collapse,
intended to steal your money & control your soul via planned obeisance.

FREE, YOUR, MIND!

(_in any case, 0.3.7 works a treat_)

**Comment by RainbowCookie32** [comment]
Cool. Go have a breakdown somewhere else please
