### ISSUE TITLE
Tries to use an invalid path in Windows and fails

### ISSUE THREAD

**Issue by guchito9** [RainbowCookie32/rusty-psn#246]
Example: BCUS98233

Log:
`INFO [rusty_psn::utils] Creating file for pkg at path "pkgs\\BCUS98233 - Uncharted 3_ Drake\'s Deception™\n1.19\\UP9000-BCUS98233_00-UNCHARTED3PATC19-A0119-V0100-PE.pkg"
ERROR [rusty_psn::cli] Download of BCUS98233 01.19 failed: The filename, directory name, or volume label syntax is incorrect. (os error 123)`

Tried with custom path with the same error:
`INFO [rusty_psn::utils] Creating file for pkg at path "E:\\roms\\BCUS98233 - Uncharted 3_ Drake\'s Deception™\n1.19\\UP9000-BCUS98233_00-UNCHARTED3PATC19-A0119-V0100-PE.pkg"
ERROR [rusty_psn::cli] Download of BCUS98233 01.19 failed: The filename, directory name, or volume label syntax is incorrect. (os error 123)`

Using latest version, either cli or gui.

**Comment by RainbowCookie32** [comment]
For who knows what reason, the game title is "Uncharted 3: Drake's Deception™
1.19".

I didn't add that newline, that's what we get apparently. I'll see what I can do about it.

**Comment by RainbowCookie32** [comment]
Added some code in #247 to remove newlines from game titles that fixes this issue, hopefully there aren't any other games doing weird things on their titles. Will tag a new release once CI passes
