### ISSUE TITLE
RPSN Not responding

### ISSUE THREAD

**Issue by SentFromHell** [RainbowCookie32/rusty-psn#252]
I downloaded TLOU Update, played for 3 hours, downloaded another game, and now rusty PSN refuses to open
![Screenshot 2024-09-25 224901](https://github.com/user-attachments/assets/d7f8aecc-2301-41e0-b663-7893f334208a)
![Screenshot_148](https://github.com/user-attachments/assets/0c8fa017-732e-4f19-9cc5-874104b0439c)

**Comment by RainbowCookie32** [comment]
Troubleshooted on Discord, turned out to be a broke egui config file. For future reference, deleting the `rusty-psn` folder on `%appdata%` fixes the issue.
