### ISSUE TITLE
Ggyhh

### ISSUE THREAD

**Issue by MarioDude64** [RainbowCookie32/rusty-psn#267]
It won't let me update a game

**Comment by RainbowCookie32** [comment]
And the award for the highest effort report goes to...

I'm gonna need more information than that to do literally anything

**Comment by MarioDude64** [comment]
After I downloaded! I put the Serial, it well have a error, and I can't fixed it!

**Comment by RainbowCookie32** [comment]
I need to know what the error is. Also, run rusty-psn again, trigger the error, close it, and post the latest .log file from the folder where you have the exe. It should be called something like rusty-psn_2024-12-01-...

**Comment by MarioDude64** [comment]
@RainbowCookie32 
![20241201_163917](https://github.com/user-attachments/assets/9bb46540-efda-43c9-bd54-d59ee61f4c3f)
![20241130_173625](https://github.com/user-attachments/assets/6d254e51-e178-491f-814a-e8a777818add)

Here's the Pictures

**Comment by RainbowCookie32** [comment]
> and post the latest .log file from the folder where you have the exe. It should be called something like rusty-psn_2024-12-01-...

In any case, I just tested locally and managed to download those just fine, so it's probably a temporary connectivity issue. Sony's servers sometimes drop the connection before the download finishes and you get an incomplete file. Try again later maybe.
![image](https://github.com/user-attachments/assets/08ac476e-ce3b-4df5-afbd-22f688b1c8a6)

**Comment by MarioDude64** [comment]
![Screenshot_20241201_184353_YouTube](https://github.com/user-attachments/assets/16c232dd-9ce5-4dd0-8f79-d1174c229ed2)

I think i'm missing this? Cause I don't see it anymore

**Comment by RainbowCookie32** [comment]
You are supposed to extract it, don't run things straight from the zip files
