### ISSUE TITLE
lbp2 special edition hash mismatch on pkg update

### ISSUE THREAD

**Issue by lbplug** [RainbowCookie32/rusty-psn#268]
tried to download the updates with the serial number and checked  i had enough storage ,some of them download but the others dont
losing hope im nearly able to play restitched online but the one thing i need doesnt work

**Comment by RainbowCookie32** [comment]
What's the game's serial? 99% of the times it's just Sony dropping the connection before the download is finished, so trying again later fixes it. But I can check on my side if there's an actual issue with rusty-psn if you post the game's serial
