### ISSUE TITLE
Reports wrong version number

### ISSUE THREAD

**Issue by ulville** [RainbowCookie32/rusty-psn#274]
rusty-psn-egui-linux Version 0.5.4 reports the version as 0.5.3 when run with --version flag. Maybe not a big deal but I've written a bash script to update it automatically and this issue causes it to misbehave

**Comment by RainbowCookie32** [comment]
Sorry, that's on me. I always forget to bump the version on the Cargo.toml file. 

I'll update dependencies later today and tag a new release with the proper version

**Comment by RainbowCookie32** [comment]
Tagged v0.5.5 with the correct version on Cargo.toml, will try to remember next time 😅
