### ISSUE TITLE
Feature Request: Add destination dir parameter

### ISSUE THREAD

**Issue by igno2k** [RainbowCookie32/rusty-psn#3]
It would be great to set the download destination dir as a parameter in the CLI version. The default is at the moment `<current directory>/pkgs`

Maybe like this:

```
# download pkgs to /tmp/pkgs
rusty-psn -s -d /tmp/pkgs -t <TITLE-ID>
```

**Comment by RainbowCookie32** [comment]
I meant to add this a while ago, but I ended up forgetting. Might give it a spin later

**Comment by RainbowCookie32** [comment]
Did a quick implementation on #4.
Please test it if you can. Seems to be working here, but I didn't push it too hard

**Comment by igno2k** [comment]
Thanks, works fine! If the directory does not exist it will be created.
The --help message / documentation should be updated as well.
