### ISSUE TITLE
rusty-psn CLI and GUI won’t run 

### ISSUE THREAD

**Issue by Schweeeeeeeeeeeeeeee** [RainbowCookie32/rusty-psn#61]
![image](https://user-images.githubusercontent.com/88291316/190874859-b310e201-9008-4eb4-ba12-a669332579b5.png)
Not sure what to do maybe my specs can help

OS: Pop!_OS 22.04 LTS x86_64
Host: MS-7B86 4.0
Kernel: 5.19.0-76051900-generic
Uptime: 1 min
Packages: 2328 (dpkg), 75 (flatpak), 
Shell: bash 5.1.16
Resolution: 2560x1440
DE: GNOME 42.3.1
WM: Mutter
WM Theme: Pop
Theme: Pop-dark [GTK2/3] 
Icons: Pop [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen 5 3600 (12) @ 4.200GHz 
GPU: NVIDIA GeForce GT 710 
Memory: 2691MiB / 15919MiB

**Comment by RainbowCookie32** [comment]
Seems to have something to do with the libssl package popOS ships with.

I'll try to workaround it

**Comment by RainbowCookie32** [comment]
Test with #62 when it's done building please

**Comment by Schweeeeeeeeeeeeeeee** [comment]
Sorry for not replying idk why i didnt.
