### ISSUE TITLE
CJK characters aren't rendered correctly

### ISSUE THREAD

**Issue by mzji** [RainbowCookie32/rusty-psn#99]
Platform: Windows 10 64-bit 21H2 Home Edition
Expected: All characters rendered correctly
Actual result:
![图片](https://user-images.githubusercontent.com/23279426/208229616-b98b22f6-def6-4238-9b98-30309bc61ad0.png)
From the image, you can see that all titles containing CJK characters are not rendered correctly (rendering as tofus instead).
For your reference, the names of the games in the image were listed below:
BLJM61267: `影牢 ～もう1人のプリンセス～`
BLJM61331: `うたわれるもの 二人の白皇`

**Comment by RainbowCookie32** [comment]
Yeah, I forgot this could happen. egui's default font doesn't include CJK characters so you get the squares instead. 

I'll look into either bundling fonts or trying to load them from the OS when I get some time.

**Comment by mzji** [comment]
One thing should be noted that when loading OS fonts, the display language of the OS should be considered as one factor of the font selection policy; for example, the default UI font of Windows with Simplified Chinese is 微软雅黑 / Microsoft YaHei, and the default UI font of Windows with Traditional Chinese is 微軟正黑體 / Microsoft JhengHei, and these two fonts are completely different.

**Comment by RainbowCookie32** [comment]
Should be fixed in #113

As I noted there, I'm bundling a Noto Sans font for Japanese, since I couldn't find any test cases for Chinese or Korean. I looked into loading system fonts, but it was probably going to be more painful than I'd like. This should work for everyone with little changes and just a few more MBs on the executable

**Comment by mzji** [comment]
Confirm fixed - though the CJK characters are smaller than the English characters.
![图片](https://user-images.githubusercontent.com/23279426/215632110-5c706eea-634d-403e-ab2b-0cba52e3ca04.png)

**Comment by RainbowCookie32** [comment]
Yeah, there seems to be a difference in size between egui's default font and Noto Sans JP, and increasing the scale of the jp font makes things look a bit wonky. I'll do some testing

**Comment by mzji** [comment]
Totally fixed now, it's awesome!
![图片](https://user-images.githubusercontent.com/23279426/215642718-385dd87e-dc98-40c3-a596-26008f9fc4a6.png)

**Comment by RainbowCookie32** [comment]
Nice, it's merge o'clock then :)
